export const countryOptions = [
  { value: 0, label: '+93', country: 'Afghanistan', flag: '🇦🇫' },
  { value: 1, label: '+358-18', country: 'Åland Islands', flag: '🇦🇽' },
  { value: 2, label: '+355', country: 'Albania', flag: '🇦🇱' },
  { value: 3, label: '+213', country: 'Algeria', flag: '🇩🇿' },
  { value: 4, label: '+1-684', country: 'American Samoa', flag: '🇦🇸' },
  { value: 5, label: '+376', country: 'Andorra', flag: '🇦🇩' },
  { value: 6, label: '+244', country: 'Angola', flag: '🇦🇴' },
  { value: 7, label: '+1-264', country: 'Anguilla', flag: '🇦🇮' },
  { value: 8, label: '+1-268', country: 'Antigua and Barbuda', flag: '🇦🇬' },
  { value: 9, label: '+54', country: 'Argentina', flag: '🇦🇷' },
  { value: 10, label: '+374', country: 'Armenia', flag: '🇦🇲' },
  { value: 11, label: '+297', country: 'Aruba', flag: '🇦🇼' },
  { value: 12, label: '+61', country: 'Australia', flag: '🇦🇺' },
  { value: 13, label: '+43', country: 'Austria', flag: '🇦🇹' },
  { value: 14, label: '+994', country: 'Azerbaijan', flag: '🇦🇿' },
  { value: 15, label: '+1-242', country: 'Bahamas', flag: '🇧🇸' },
  { value: 16, label: '+973', country: 'Bahrain', flag: '🇧🇭' },
  { value: 17, label: '+880', country: 'Bangladesh', flag: '🇧🇩' },
  { value: 18, label: '+1-246', country: 'Barbados', flag: '🇧🇧' },
  { value: 19, label: '+375', country: 'Belarus', flag: '🇧🇾' },
  { value: 20, label: '+32', country: 'Belgium', flag: '🇧🇪' },
  { value: 21, label: '+501', country: 'Belize', flag: '🇧🇿' },
  { value: 22, label: '+229', country: 'Benin', flag: '🇧🇯' },
  { value: 23, label: '+1-441', country: 'Bermuda', flag: '🇧🇲' },
  { value: 24, label: '+975', country: 'Bhutan', flag: '🇧🇹' },
  { value: 25, label: '+591', country: 'Bolivia', flag: '🇧🇴' },
  { value: 26, label: '+387', country: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { value: 27, label: '+267', country: 'Botswana', flag: '🇧🇼' },
  { value: 28, label: '+55', country: 'Brazil', flag: '🇧🇷' },
  { value: 29, label: '+673', country: 'Brunei Darussalam', flag: '🇧🇳' },
  { value: 30, label: '+359', country: 'Bulgaria', flag: '🇧🇬' },
  { value: 31, label: '+226', country: 'Burkina Faso', flag: '🇧🇫' },
  { value: 32, label: '+257', country: 'Burundi', flag: '🇧🇮' },
  { value: 33, label: '+238', country: 'Cabo Verde', flag: '🇨🇻' },
  { value: 34, label: '+855', country: 'Cambodia', flag: '🇰🇭' },
  { value: 35, label: '+237', country: 'Cameroon', flag: '🇨🇲' },
  { value: 36, label: '+1', country: 'Canada', flag: '🇨🇦' },
  { value: 37, label: '+1-345', country: 'Cayman Islands', flag: '🇰🇾' },
  { value: 38, label: '+236', country: 'Central African Republic', flag: '🇨🇫' },
  { value: 39, label: '+235', country: 'Chad', flag: '🇹🇩' },
  { value: 40, label: '+56', country: 'Chile', flag: '🇨🇱' },
  { value: 41, label: '+86', country: 'China', flag: '🇨🇳' },
  { value: 42, label: '+57', country: 'Colombia', flag: '🇨🇴' },
  { value: 43, label: '+269', country: 'Comoros', flag: '🇰🇲' },
  { value: 44, label: '+242', country: 'Congo (Republic)', flag: '🇨🇬' },
  {
    value: 45,
    label: '+243',
    country: 'Congo (Democratic Republic)',
    flag: '🇨🇩',
  },
  { value: 46, label: '+682', country: 'Cook Islands', flag: '🇨🇰' },
  { value: 47, label: '+506', country: 'Costa Rica', flag: '🇨🇷' },
  { value: 48, label: '+225', country: "Côte d'Ivoire", flag: '🇨🇮' },
  { value: 49, label: '+385', country: 'Croatia', flag: '🇭🇷' },
  { value: 50, label: '+53', country: 'Cuba', flag: '🇨🇺' },
  { value: 51, label: '+599-9', country: 'Curaçao', flag: '🇨🇼' },
  { value: 52, label: '+357', country: 'Cyprus', flag: '🇨🇾' },
  { value: 53, label: '+420', country: 'Czech Republic', flag: '🇨🇿' },
  { value: 54, label: '+45', country: 'Denmark', flag: '🇩🇰' },
  { value: 55, label: '+253', country: 'Djibouti', flag: '🇩🇯' },
  { value: 56, label: '+1-767', country: 'Dominica', flag: '🇩🇲' },
  { value: 57, label: '+1-809', country: 'Dominican Republic', flag: '🇩🇴' },
  { value: 58, label: '+593', country: 'Ecuador', flag: '🇪🇨' },
  { value: 59, label: '+20', country: 'Egypt', flag: '🇪🇬' },
  { value: 60, label: '+503', country: 'El Salvador', flag: '🇸🇻' },
  { value: 61, label: '+240', country: 'Equatorial Guinea', flag: '🇬🇶' },
  { value: 62, label: '+291', country: 'Eritrea', flag: '🇪🇷' },
  { value: 63, label: '+372', country: 'Estonia', flag: '🇪🇪' },
  { value: 64, label: '+268', country: 'Eswatini (Swaziland)', flag: '🇸🇿' },
  { value: 65, label: '+251', country: 'Ethiopia', flag: '🇪🇹' },
  {
    value: 66,
    label: '+500',
    country: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
  },
  { value: 67, label: '+298', country: 'Faroe Islands', flag: '🇫🇴' },
  { value: 68, label: '+679', country: 'Fiji', flag: '🇫🇯' },
  { value: 69, label: '+358', country: 'Finland', flag: '🇫🇮' },
  { value: 70, label: '+33', country: 'France', flag: '🇫🇷' },
  { value: 71, label: '+594', country: 'French Guiana', flag: '🇬🇫' },
  { value: 72, label: '+689', country: 'French Polynesia', flag: '🇵🇫' },
  { value: 73, label: '+241', country: 'Gabon', flag: '🇬🇦' },
  { value: 74, label: '+220', country: 'Gambia', flag: '🇬🇲' },
  { value: 75, label: '+995', country: 'Georgia', flag: '🇬🇪' },
  { value: 76, label: '+49', country: 'Germany', flag: '🇩🇪' },
  { value: 77, label: '+233', country: 'Ghana', flag: '🇬🇭' },
  { value: 78, label: '+350', country: 'Gibraltar', flag: '🇬🇮' },
  { value: 79, label: '+30', country: 'Greece', flag: '🇬🇷' },
  { value: 80, label: '+299', country: 'Greenland', flag: '🇬🇱' },
  { value: 81, label: '+1-473', country: 'Grenada', flag: '🇬🇩' },
  { value: 82, label: '+590', country: 'Guadeloupe', flag: '🇬🇵' },
  { value: 83, label: '+1-671', country: 'Guam', flag: '🇬🇺' },
  { value: 84, label: '+502', country: 'Guatemala', flag: '🇬🇹' },
  { value: 85, label: '+44-1481', country: 'Guernsey', flag: '🇬🇬' },
  { value: 86, label: '+224', country: 'Guinea', flag: '🇬🇳' },
  { value: 87, label: '+245', country: 'Guinea-Bissau', flag: '🇬🇼' },
  { value: 88, label: '+592', country: 'Guyana', flag: '🇬🇾' },
  { value: 89, label: '+509', country: 'Haiti', flag: '🇭🇹' },
  { value: 90, label: '+504', country: 'Honduras', flag: '🇭🇳' },
  { value: 91, label: '+852', country: 'Hong Kong', flag: '🇭🇰' },
  { value: 92, label: '+36', country: 'Hungary', flag: '🇭🇺' },
  { value: 93, label: '+354', country: 'Iceland', flag: '🇮🇸' },
  { value: 94, label: '+91', country: 'India', flag: '🇮🇳' },
  { value: 95, label: '+62', country: 'Indonesia', flag: '🇮🇩' },
  { value: 96, label: '+98', country: 'Iran', flag: '🇮🇷' },
  { value: 97, label: '+964', country: 'Iraq', flag: '🇮🇶' },
  { value: 98, label: '+353', country: 'Ireland', flag: '🇮🇪' },
  { value: 99, label: '+44-1624', country: 'Isle of Man', flag: '🇮🇲' },
  { value: 100, label: '+972', country: 'Israel', flag: '🇮🇱' },
  { value: 101, label: '+39', country: 'Italy', flag: '🇮🇹' },
  { value: 102, label: '+1-876', country: 'Jamaica', flag: '🇯🇲' },
  { value: 103, label: '+81', country: 'Japan', flag: '🇯🇵' },
  { value: 104, label: '+44-1534', country: 'Jersey', flag: '🇯🇪' },
  { value: 105, label: '+962', country: 'Jordan', flag: '🇯🇴' },
  { value: 106, label: '+7', country: 'Kazakhstan', flag: '🇰🇿' },
  { value: 107, label: '+254', country: 'Kenya', flag: '🇰🇪' },
  { value: 108, label: '+686', country: 'Kiribati', flag: '🇰🇮' },
  { value: 109, label: '+850', country: 'Korea (North)', flag: '🇰🇵' },
  { value: 110, label: '+82', country: 'Korea (South)', flag: '🇰🇷' },
  { value: 111, label: '+383', country: 'Kosovo', flag: '🇽🇰' },
  { value: 112, label: '+965', country: 'Kuwait', flag: '🇰🇼' },
  { value: 113, label: '+996', country: 'Kyrgyzstan', flag: '🇰🇬' },
  { value: 114, label: '+856', country: 'Laos', flag: '🇱🇦' },
  { value: 115, label: '+371', country: 'Latvia', flag: '🇱🇻' },
  { value: 116, label: '+961', country: 'Lebanon', flag: '🇱🇧' },
  { value: 117, label: '+266', country: 'Lesotho', flag: '🇱🇸' },
  { value: 118, label: '+231', country: 'Liberia', flag: '🇱🇷' },
  { value: 119, label: '+218', country: 'Libya', flag: '🇱🇾' },
  { value: 120, label: '+423', country: 'Liechtenstein', flag: '🇱🇮' },
  { value: 121, label: '+370', country: 'Lithuania', flag: '🇱🇹' },
  { value: 122, label: '+352', country: 'Luxembourg', flag: '🇱🇺' },
  { value: 123, label: '+853', country: 'Macao', flag: '🇲🇴' },
  { value: 124, label: '+389', country: 'North Macedonia', flag: '🇲🇰' },
  { value: 125, label: '+261', country: 'Madagascar', flag: '🇲🇬' },
  { value: 126, label: '+265', country: 'Malawi', flag: '🇲🇼' },
  { value: 127, label: '+60', country: 'Malaysia', flag: '🇲🇾' },
  { value: 128, label: '+960', country: 'Maldives', flag: '🇲🇻' },
  { value: 129, label: '+223', country: 'Mali', flag: '🇲🇱' },
  { value: 130, label: '+356', country: 'Malta', flag: '🇲🇹' },
  { value: 131, label: '+692', country: 'Marshall Islands', flag: '🇲🇭' },
  { value: 132, label: '+596', country: 'Martinique', flag: '🇲🇶' },
  { value: 133, label: '+222', country: 'Mauritania', flag: '🇲🇷' },
  { value: 134, label: '+230', country: 'Mauritius', flag: '🇲🇺' },
  { value: 135, label: '+262', country: 'Mayotte', flag: '🇾🇹' },
  { value: 136, label: '+52', country: 'Mexico', flag: '🇲🇽' },
  { value: 137, label: '+691', country: 'Micronesia', flag: '🇫🇲' },
  { value: 138, label: '+373', country: 'Moldova', flag: '🇲🇩' },
  { value: 139, label: '+377', country: 'Monaco', flag: '🇲🇨' },
  { value: 140, label: '+976', country: 'Mongolia', flag: '🇲🇳' },
  { value: 141, label: '+382', country: 'Montenegro', flag: '🇲🇪' },
  { value: 142, label: '+1-664', country: 'Montserrat', flag: '🇲🇸' },
  { value: 143, label: '+212', country: 'Morocco', flag: '🇲🇦' },
  { value: 144, label: '+258', country: 'Mozambique', flag: '🇲🇿' },
  { value: 145, label: '+95', country: 'Myanmar (Burma)', flag: '🇲🇲' },
  { value: 146, label: '+264', country: 'Namibia', flag: '🇳🇦' },
  { value: 147, label: '+674', country: 'Nauru', flag: '🇳🇷' },
  { value: 148, label: '+977', country: 'Nepal', flag: '🇳🇵' },
  { value: 149, label: '+31', country: 'Netherlands', flag: '🇳🇱' },
  { value: 150, label: '+687', country: 'New Caledonia', flag: '🇳🇨' },
  { value: 151, label: '+64', country: 'New Zealand', flag: '🇳🇿' },
  { value: 152, label: '+505', country: 'Nicaragua', flag: '🇳🇮' },
  { value: 153, label: '+227', country: 'Niger', flag: '🇳🇪' },
  { value: 154, label: '+234', country: 'Nigeria', flag: '🇳🇬' },
  { value: 155, label: '+683', country: 'Niue', flag: '🇳🇺' },
  { value: 156, label: '+672', country: 'Norfolk Island', flag: '🇳🇫' },
  {
    value: 157,
    label: '+1-670',
    country: 'Northern Mariana Islands',
    flag: '🇲🇵',
  },
  { value: 158, label: '+47', country: 'Norway', flag: '🇳🇴' },
  { value: 159, label: '+968', country: 'Oman', flag: '🇴🇲' },
  { value: 160, label: '+92', country: 'Pakistan', flag: '🇵🇰' },
  { value: 161, label: '+680', country: 'Palau', flag: '🇵🇼' },
  { value: 162, label: '+970', country: 'Palestine', flag: '🇵🇸' },
  { value: 163, label: '+507', country: 'Panama', flag: '🇵🇦' },
  { value: 164, label: '+675', country: 'Papua New Guinea', flag: '🇵🇬' },
  { value: 165, label: '+595', country: 'Paraguay', flag: '🇵🇾' },
  { value: 166, label: '+51', country: 'Peru', flag: '🇵🇪' },
  { value: 167, label: '+63', country: 'Philippines', flag: '🇵🇭' },
  { value: 168, label: '+48', country: 'Poland', flag: '🇵🇱' },
  { value: 169, label: '+351', country: 'Portugal', flag: '🇵🇹' },
  { value: 170, label: '+1-787', country: 'Puerto Rico', flag: '🇵🇷' },
  { value: 171, label: '+974', country: 'Qatar', flag: '🇶🇦' },
  { value: 172, label: '+262', country: 'Réunion', flag: '🇷🇪' },
  { value: 173, label: '+40', country: 'Romania', flag: '🇷🇴' },
  { value: 174, label: '+7', country: 'Russia', flag: '🇷🇺' },
  { value: 175, label: '+250', country: 'Rwanda', flag: '🇷🇼' },
  { value: 176, label: '+590-590', country: 'Saint Barthélemy', flag: '🇧🇱' },
  {
    value: 177,
    label: '+290',
    country: 'Saint Helena, Ascension and Tristan da Cunha',
    flag: '🇸🇭',
  },
  { value: 178, label: '+1-869', country: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { value: 179, label: '+1-758', country: 'Saint Lucia', flag: '🇱🇨' },
  {
    value: 180,
    label: '+590-690',
    country: 'Saint Martin (French part)',
    flag: '🇲🇫',
  },
  {
    value: 181,
    label: '+508',
    country: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
  },
  {
    value: 182,
    label: '+1-784',
    country: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
  },
  { value: 183, label: '+685', country: 'Samoa', flag: '🇼🇸' },
  { value: 184, label: '+378', country: 'San Marino', flag: '🇸🇲' },
  { value: 185, label: '+239', country: 'Sao Tome and Principe', flag: '🇸🇹' },
  { value: 186, label: '+966', country: 'Saudi Arabia', flag: '🇸🇦' },
  { value: 187, label: '+221', country: 'Senegal', flag: '🇸🇳' },
  { value: 188, label: '+381', country: 'Serbia', flag: '🇷🇸' },
  { value: 189, label: '+248', country: 'Seychelles', flag: '🇸🇨' },
  { value: 190, label: '+232', country: 'Sierra Leone', flag: '🇸🇱' },
  { value: 191, label: '+65', country: 'Singapore', flag: '🇸🇬' },
  {
    value: 192,
    label: '+1-721',
    country: 'Sint Maarten (Dutch part)',
    flag: '🇸🇽',
  },
  { value: 193, label: '+421', country: 'Slovakia', flag: '🇸🇰' },
  { value: 194, label: '+386', country: 'Slovenia', flag: '🇸🇮' },
  { value: 195, label: '+677', country: 'Solomon Islands', flag: '🇸🇧' },
  { value: 196, label: '+252', country: 'Somalia', flag: '🇸🇴' },
  { value: 197, label: '+27', country: 'South Africa', flag: '🇿🇦' },
  {
    value: 198,
    label: '+500',
    country: 'South Georgia & South Sandwich Islands',
    flag: '🇬🇸',
  },
  { value: 199, label: '+211', country: 'South Sudan', flag: '🇸🇸' },
  { value: 200, label: '+34', country: 'Spain', flag: '🇪🇸' },
  { value: 201, label: '+94', country: 'Sri Lanka', flag: '🇱🇰' },
  { value: 202, label: '+249', country: 'Sudan', flag: '🇸🇩' },
  { value: 203, label: '+597', country: 'Suriname', flag: '🇸🇷' },
  {
    value: 204,
    label: '+47-79',
    country: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
  },
  { value: 205, label: '+46', country: 'Sweden', flag: '🇸🇪' },
  { value: 206, label: '+41', country: 'Switzerland', flag: '🇨🇭' },
  { value: 207, label: '+963', country: 'Syrian Arab Republic', flag: '🇸🇾' },
  { value: 208, label: '+886', country: 'Taiwan', flag: '🇹🇼' },
  { value: 209, label: '+992', country: 'Tajikistan', flag: '🇹🇯' },
  { value: 210, label: '+255', country: 'Tanzania', flag: '🇹🇿' },
  { value: 211, label: '+66', country: 'Thailand', flag: '🇹🇭' },
  { value: 212, label: '+670', country: 'Timor-Leste', flag: '🇹🇱' },
  { value: 213, label: '+228', country: 'Togo', flag: '🇹🇬' },
  { value: 214, label: '+690', country: 'Tokelau', flag: '🇹🇰' },
  { value: 215, label: '+676', country: 'Tonga', flag: '🇹🇴' },
  { value: 216, label: '+1-868', country: 'Trinidad and Tobago', flag: '🇹🇹' },
  { value: 217, label: '+216', country: 'Tunisia', flag: '🇹🇳' },
  { value: 218, label: '+90', country: 'Turkey', flag: '🇹🇷' },
  { value: 219, label: '+993', country: 'Turkmenistan', flag: '🇹🇲' },
  {
    value: 220,
    label: '+1-649',
    country: 'Turks and Caicos Islands',
    flag: '🇹🇨',
  },
  { value: 221, label: '+688', country: 'Tuvalu', flag: '🇹🇻' },
  { value: 222, label: '+256', country: 'Uganda', flag: '🇺🇬' },
  { value: 223, label: '+380', country: 'Ukraine', flag: '🇺🇦' },
  { value: 224, label: '+971', country: 'United Arab Emirates', flag: '🇦🇪' },
  { value: 225, label: '+44', country: 'United Kingdom', flag: '🇬🇧' },
  { value: 226, label: '+1', country: 'United States', flag: '🇺🇸' },
  { value: 227, label: '+598', country: 'Uruguay', flag: '🇺🇾' },
  { value: 228, label: '+1', country: 'US Minor Outlying Islands', flag: '🇺🇸' },
  { value: 229, label: '+998', country: 'Uzbekistan', flag: '🇺🇿' },
  { value: 230, label: '+678', country: 'Vanuatu', flag: '🇻🇺' },
  {
    value: 231,
    label: '+39-06',
    country: 'Vatican City (Holy See)',
    flag: '🇻🇦',
  },
  { value: 232, label: '+58', country: 'Venezuela', flag: '🇻🇪' },
  { value: 233, label: '+84', country: 'Vietnam', flag: '🇻🇳' },
  {
    value: 234,
    label: '+1-284',
    country: 'Virgin Islands (British)',
    flag: '🇻🇬',
  },
  { value: 235, label: '+1-340', country: 'Virgin Islands (U.S.)', flag: '🇻🇮' },
  { value: 236, label: '+681', country: 'Wallis and Futuna', flag: '🇼🇫' },
  { value: 237, label: '+212', country: 'Western Sahara', flag: '🇪🇭' },
  { value: 238, label: '+967', country: 'Yemen', flag: '🇾🇪' },
  { value: 239, label: '+260', country: 'Zambia', flag: '🇿🇲' },
  { value: 240, label: '+263', country: 'Zimbabwe', flag: '🇿🇼' },
];
